<?php
return [
	'mode'                  => 'utf-8',
    'format'                => 'A7',
    'orientation'           => 'L',
	'default_font_size'    => '10',
	'default_font'         => 'arial',
	'margin_left'          => 2,
	'margin_right'         => 2,
	'margin_top'           => 2,
	'margin_bottom'        => 2,
	'margin_header'        => 0,
	'margin_footer'        => 0,
	'title'                => 'Laravel mPDF',
	'author'               => '',
	'watermark'            => '',
	'show_watermark'       => false,
	'watermark_font'       => 'sans-serif',
	'display_mode'         => 'fullpage',
	'watermark_text_alpha' => 0.1,
	'custom_font_dir'      => '',
	'custom_font_data' 	   => [],
	'auto_language_detection'  => false,
	'temp_dir'               => '',
	'pdfa' 			=> false,
    'pdfaauto' 		=> false,
];